version: '1'
services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgres://user:password@postgres:5432/mydatabase
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - postgres
  
  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend
  
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: